import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Language = 'es' | 'en';

export interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const STORAGE_KEY = 'realestate_language';

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.catalog': 'Catálogo',
    'nav.agents': 'Agentes',
    'nav.mortgage': 'Simulador RD$',
    'nav.map': 'Mapa',
    'nav.compare': 'Comparador',
    'nav.myPanel': 'Mi Panel',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',

    // Sidebar & Portals
    'sidebar.portalClient': 'Portal del Cliente',
    'sidebar.portalOwner': 'Propietario Directo',
    'sidebar.portalAgent': 'Portal del Agente',
    'sidebar.portalAdmin': 'Administración del Sistema',
    'sidebar.portalDev': 'Portal del Desarrollador',
    'sidebar.panelClient': 'Panel Cliente',
    'sidebar.panelOwner': 'Panel Propietario',
    'sidebar.panelAgent': 'Panel Agente',
    'sidebar.panelAdmin': 'Panel Admin',
    'sidebar.panelDev': 'Panel Dev',
    'sidebar.panelMenu': 'Menú Panel',
    'sidebar.overview': 'Resumen',
    'sidebar.favorites': 'Mis Favoritos',
    'sidebar.offers': 'Mis Ofertas',
    'sidebar.appointments': 'Mis Citas',
    'sidebar.buyAbility': 'Capacidad de Compra',
    'sidebar.savedSearches': 'Búsquedas Guardadas',
    'sidebar.messages': 'Mensajes Directos',
    'sidebar.profile': 'Mi Perfil',
    'sidebar.myProperties': 'Mis Inmuebles',
    'sidebar.publishDirect': 'Publicar Directo',
    'sidebar.receivedOffers': 'Ofertas Recibidas',
    'sidebar.properties': 'Mis Propiedades',
    'sidebar.leadPipeline': 'Pipeline de Prospectos',
    'sidebar.calendar': 'Calendario de Citas',
    'sidebar.commissions': 'Mis Comisiones',
    'sidebar.documents': 'Documentos y KYC',
    'sidebar.subscription': 'Mi Suscripción',
    'sidebar.reviews': 'Mis Reseñas',
    'sidebar.systemKpis': 'KPIs y Métricas',
    'sidebar.allProperties': 'Todas las Propiedades',
    'sidebar.manageAgents': 'Gestionar Agentes',
    'sidebar.reassignPortfolio': 'Reasignar Cartera',
    'sidebar.verifications': 'Verificaciones KYC',
    'sidebar.users': 'Directorio de Usuarios',
    'sidebar.propertyTypes': 'Tipos de Propiedad',
    'sidebar.saleTypes': 'Tipos de Venta',
    'sidebar.improvements': 'Amenidades',
    'sidebar.managePlans': 'Planes de Suscripción',
    'sidebar.manageAdmins': 'Administradores',
    'sidebar.manageDevs': 'Desarrolladores',
    'sidebar.auditActivity': 'Auditoría del Sistema',
    'sidebar.apiPortal': 'Portal de API',
    'sidebar.apiDocs': 'Documentación Swagger',
    'sidebar.rawCatalogs': 'Catálogos RAW',
    'sidebar.roleAdmin': 'Administrador',
    'sidebar.roleAgent': 'Agente',
    'sidebar.roleOwner': 'Propietario',
    'sidebar.roleDeveloper': 'Desarrollador',
    'sidebar.roleClient': 'Cliente',

    // Home Page
    'home.badge': 'Ecosistema Inmobiliario de Alto Rendimiento en RD$',
    'home.title': 'Encuentra, Negocia y Cierra tu Inmueble Soñado en',
    'home.country': 'República Dominicana',
    'home.subtitle': 'Catálogo verificado con transacciones garantizadas, simulación hipotecaria en cuotas fijas bajo el sistema francés y cierre atómico de ofertas.',
    'home.searchAi': 'Búsqueda Inteligente con IA (NLP)',
    'home.searchQuick': 'Búsqueda Rápida',
    'home.typeLabel': 'Tipo de Propiedad',
    'home.allTypes': 'Todos los tipos',
    'home.saleLabel': 'Modalidad',
    'home.allSales': 'Todas',
    'home.codeLabel': 'Código de Propiedad',
    'home.codePlaceholder': 'Ej. 102030',
    'home.exploreBtn': 'Explorar Propiedades',
    'home.statsProps': 'Inmuebles Activos',
    'home.statsClients': 'Clientes Satisfechos',
    'home.statsRate': 'Tasa Promedio Fija',
    'home.statsSecurity': 'Transacciones Seguras',
    'home.featuredTitle': 'Propiedades Destacadas',
    'home.featuredSubtitle': 'Selección exclusiva de inmuebles listos para venta y cierre inmediato en pesos dominicanos.',
    'home.viewAll': 'Ver Catálogo Completo',
    'home.whyTitle': '¿Por Qué Elegir RealEstateApp?',
    'home.whySubtitle': 'Un ecosistema diseñado para maximizar la certidumbre en cada etapa de la compraventa.',
    'home.why1Title': 'Simulación Hipotecaria Bancaria',
    'home.why1Desc': 'Cálculo transparente en cuotas fijas bajo el sistema francés en pesos dominicanos (RD$) con tabla amortizada descargable.',
    'home.why2Title': 'Cierre Atómico de Ofertas',
    'home.why2Desc': 'Aceptación de oferta garantizada con cancelación automática en cascada y consistencia transaccional ACID.',
    'home.why3Title': 'Agentes Inmobiliarios Verificados',
    'home.why3Desc': 'Fuerza de ventas certificada con validación KYC, atención personalizada y chat bidireccional en vivo.',
    'home.agentsTitle': 'Corredores Inmobiliarios Certificados',
    'home.agentsSubtitle': 'Conoce a nuestro equipo de agentes profesionales dedicados a brindarte asesoría de primer nivel.',
    'home.viewAgents': 'Ver Todos los Agentes',
    'home.ctaTitle': '¿Eres Propietario o Desarrollador?',
    'home.ctaSubtitle': 'Publica tus propiedades en nuestra plataforma y conecta con miles de compradores e inversionistas calificados.',
    'home.ctaStart': 'Comenzar Ahora',
    'home.ctaContact': 'Contactar Ventas',

    // AI Search
    'ai.searchMode': 'Búsqueda Inteligente con IA (NLP)',
    'ai.standardMode': 'Búsqueda Estándar',
    'ai.button': 'Buscar con IA',
    'ai.buttonShort': 'Buscar',
    'ai.analyzing': 'Interpretando...',
    'ai.extracting': 'Extrayendo intenciones, rangos de precio, habitaciones y zonas en tiempo real...',
    'ai.confidence': 'Confianza:',
    'ai.matches': 'coincidencias',
    'ai.match': 'coincidencia',
    'ai.placeholder': "Escribe libremente: Ej. 'Apartamento de 3 habitaciones en Bella Vista con balcón por menos de 8M'...",
    'ai.suggestions': 'Sugerencias:',
    'ai.understood': 'Interpretado como:',
    'ai.apply': 'Aplicar Filtros',

    'catalog.badge': 'Catálogo Oficial de Inmuebles',
    'catalog.title': 'Propiedades Exclusivas en RD$',
    'catalog.subtitle': 'Filtra por tipo, ubicación, amenidades, habitaciones y rango de precios con cálculo hipotecario en tiempo real.',
    'catalog.filters': 'Filtros',
    'catalog.activeFilters': 'Filtros activos:',
    'catalog.clearFilters': 'Limpiar filtros',
    'catalog.clearAll': 'Limpiar todo',
    'catalog.noResults': 'No se encontraron propiedades con los criterios seleccionados.',
    'catalog.showing': 'Mostrando',
    'catalog.properties': 'inmuebles',
    'catalog.resultsCount': 'propiedades encontradas',
    'catalog.sortBy': 'Ordenar por:',
    'catalog.sortFeatured': 'Destacadas Primero',
    'catalog.sortPriceAsc': 'Precio: Menor a Mayor',
    'catalog.sortPriceDesc': 'Precio: Mayor a Menor',
    'catalog.sortBedrooms': 'Más Habitaciones',
    'catalog.sortRecent': 'Más Recientes',
    'catalog.saveSearch': 'Guardar Búsqueda',
    'catalog.viewGrid': 'Cuadrícula',
    'catalog.viewList': 'Lista',
    'catalog.loading': 'Consultando catálogo en vivo...',
    'catalog.emptyTitle': 'No se encontraron propiedades con los filtros seleccionados',
    'catalog.emptyDesc': 'Intenta ajustar los criterios de búsqueda, ampliar el rango de precios en RD$ o limpiar los filtros.',
    'catalog.modalTitle': 'Guardar Búsqueda',
    'catalog.modalPlaceholder': 'Nombre de la búsqueda',
    'catalog.modalEmailAlerts': 'Recibir alertas por correo',
    'catalog.cancel': 'Cancelar',
    'catalog.save': 'Guardar',

    // Filter Component
    'filter.title': 'Filtros Avanzados',
    'filter.reset': 'Limpiar',
    'filter.code': 'Código de Propiedad',
    'filter.codePlaceholder': 'Ej. 102030',
    'filter.type': 'Tipo de Propiedad',
    'filter.allTypes': 'Todos los tipos',
    'filter.saleType': 'Modalidad de Venta',
    'filter.allSales': 'Todas las modalidades',
    'filter.priceRange': 'Rango de Precios',
    'filter.minPrice': 'Precio Mín',
    'filter.maxPrice': 'Precio Máx',
    'filter.rooms': 'Habitaciones',
    'filter.any': 'Cualquiera',
    'filter.orMore': 'o más',
    'filter.bathrooms': 'Baños',
    'filter.location': 'Ubicación',
    'filter.province': 'Provincia',
    'filter.allProvinces': 'Todas las provincias',
    'filter.municipality': 'Municipio',
    'filter.allMunicipalities': 'Todos los municipios',
    'filter.sector': 'Sector',
    'filter.sectorPlaceholder': 'Ej. Naco, Piantini, Bella Vista...',
    'filter.nearMe': 'Cerca de mí',
    'filter.maxDistance': 'Distancia máxima (km)',
    'filter.amenities': 'Mejoras / Amenidades',
    'filter.agent': 'Agente Inmobiliario',
    'filter.allAgents': 'Todos los agentes',
    'filter.onlyFeatured': 'Solo Destacadas',
    'filter.onlyVerified': 'Solo Agentes Verificados',
    'filter.onlyFinanciable': 'Solo Financiables',
    'filter.onlyVirtualTour': 'Con Tour 360°',

    // Property Card & Details
    'property.featured': 'Destacada',
    'property.rooms': 'Hab.',
    'property.bathrooms': 'Baños',
    'property.size': 'm²',
    'property.viewDetails': 'Ver Detalles',
    'property.makeOffer': 'Hacer Oferta',
    'property.bookAppointment': 'Agendar Cita',
    'property.virtualTour': 'Tour 360°',
    'property.estimatedInstallment': 'Cuota estimada',
    'property.perMonth': '/mes',
    'property.compare': 'Comparar',
    'property.favoritePrompt': 'Inicia sesión como Cliente para guardar favoritos.',

    // Mortgage Simulator
    'mortgage.title': 'Simulador Hipotecario (RD$)',
    'mortgage.subtitle': 'Sistema Francés de Amortización con cuota fija mensual en Pesos Dominicanos.',
    'mortgage.propertyPrice': 'Precio del Inmueble',
    'mortgage.downPayment': 'Inicial',
    'mortgage.interestRate': 'Tasa de Interés Anual',
    'mortgage.termYears': 'Plazo en Años',
    'mortgage.monthlyPayment': 'Cuota Mensual Estimada',
    'mortgage.totalLoan': 'Monto Financiado',
    'mortgage.totalInterest': 'Total Intereses',
    'mortgage.totalPayment': 'Pago Total (Capital + Interés)',
    'mortgage.viewSchedule': 'Ver Tabla de Amortización',
    'mortgage.hideSchedule': 'Ocultar Tabla',
    'mortgage.disclaimer': 'Cálculo orientativo sin seguros bancarios (seguro de vida / propiedad no incluidos).',
    'mortgage.scheduleTitle': 'Tabla de Amortización Francesa (Cuota Fija)',
    'mortgage.loanTerm': 'Plazo del Préstamo',
    'mortgage.years': 'Años',
    'mortgage.months': 'meses',
    'mortgage.yearsAbbr': 'a',
    'mortgage.fixedInstallment': 'Cuota Fija Mensual',
    'mortgage.forMonths': 'Por',
    'mortgage.capitalToFinance': 'Capital a Financiar',
    'mortgage.totalCost': 'Costo Total del Crédito',
    'mortgage.financialCost': 'Costo financiero acumulado',
    'mortgage.capitalPlusInterest': 'Capital + Intereses',
    'mortgage.fullSchedule': 'Ver Tabla de Amortización Completa',
    'mortgage.hideTable': 'Ocultar Tabla de Amortización',
    'mortgage.tableTitle': 'Tabla de Cuotas Mensuales — Año',
    'mortgage.tableSubtitle': 'Desglose de amortización del capital y distribución de intereses.',
    'mortgage.print': 'Imprimir / PDF',
    'mortgage.month': 'Mes',
    'mortgage.fixedInstallmentCol': 'Cuota Fija (RD$)',
    'mortgage.interestCol': 'Interés (RD$)',
    'mortgage.principalCol': 'Capital (RD$)',
    'mortgage.balanceCol': 'Balance Restante (RD$)',
    'mortgage.prevYear': 'Año Anterior',
    'mortgage.nextYear': 'Siguiente Año',
    'mortgage.of': 'de',
    'mortgage.year': 'Año',
    'mortgage.annualPayment': 'Cuota Anual',
    'mortgage.principal': 'Capital',
    'mortgage.interest': 'Interés',
    'mortgage.balance': 'Saldo Restante',
    'mortgage.downloadPdf': 'Descargar Tabla',

    // Statuses
    'status.available': 'Disponible',
    'status.reserved': 'Reservada',
    'status.sold': 'Vendida',
    'status.pending': 'Pendiente',
    'status.accepted': 'Aceptada',
    'status.rejected': 'Rechazada',
    'status.scheduled': 'Programada',
    'status.confirmed': 'Confirmada',
    'status.completed': 'Completada',
    'status.cancelled': 'Cancelada',

    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.close': 'Cerrar',
    'common.actions': 'Acciones',
    'common.details': 'Detalles',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.yes': 'Sí',
    'common.no': 'No',
  },
  en: {
    // Navigation
    'nav.catalog': 'Catalog',
    'nav.agents': 'Agents',
    'nav.mortgage': 'Mortgage (RD$)',
    'nav.map': 'Map',
    'nav.compare': 'Compare',
    'nav.myPanel': 'Dashboard',
    'nav.login': 'Sign In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',

    // Sidebar & Portals
    'sidebar.portalClient': 'Client Portal',
    'sidebar.portalOwner': 'Direct Owner Portal',
    'sidebar.portalAgent': 'Agent Portal',
    'sidebar.portalAdmin': 'System Administration',
    'sidebar.portalDev': 'Developer Portal',
    'sidebar.panelClient': 'Client Panel',
    'sidebar.panelOwner': 'Owner Panel',
    'sidebar.panelAgent': 'Agent Panel',
    'sidebar.panelAdmin': 'Admin Panel',
    'sidebar.panelDev': 'Dev Panel',
    'sidebar.panelMenu': 'Dashboard Menu',
    'sidebar.overview': 'Overview',
    'sidebar.favorites': 'My Favorites',
    'sidebar.offers': 'My Offers',
    'sidebar.appointments': 'My Appointments',
    'sidebar.buyAbility': 'Buying Ability',
    'sidebar.savedSearches': 'Saved Searches',
    'sidebar.messages': 'Direct Messages',
    'sidebar.profile': 'My Profile',
    'sidebar.myProperties': 'My Properties',
    'sidebar.publishDirect': 'Publish Listing',
    'sidebar.receivedOffers': 'Received Offers',
    'sidebar.properties': 'My Properties',
    'sidebar.leadPipeline': 'Lead Pipeline',
    'sidebar.calendar': 'Appointments Calendar',
    'sidebar.commissions': 'My Commissions',
    'sidebar.documents': 'Documents & KYC',
    'sidebar.subscription': 'My Subscription',
    'sidebar.reviews': 'My Reviews',
    'sidebar.systemKpis': 'KPIs & Metrics',
    'sidebar.allProperties': 'All Properties',
    'sidebar.manageAgents': 'Manage Agents',
    'sidebar.reassignPortfolio': 'Reassign Portfolio',
    'sidebar.verifications': 'KYC Verifications',
    'sidebar.users': 'User Directory',
    'sidebar.propertyTypes': 'Property Types',
    'sidebar.saleTypes': 'Sale Types',
    'sidebar.improvements': 'Amenities',
    'sidebar.managePlans': 'Subscription Plans',
    'sidebar.manageAdmins': 'Administrators',
    'sidebar.manageDevs': 'Developers',
    'sidebar.auditActivity': 'System Audit',
    'sidebar.apiPortal': 'API Portal',
    'sidebar.apiDocs': 'Swagger Docs',
    'sidebar.rawCatalogs': 'RAW Catalogs',
    'sidebar.roleAdmin': 'Administrator',
    'sidebar.roleAgent': 'Agent',
    'sidebar.roleOwner': 'Owner',
    'sidebar.roleDeveloper': 'Developer',
    'sidebar.roleClient': 'Client',

    // Home Page
    'home.badge': 'High-Performance Real Estate Ecosystem in DR',
    'home.title': 'Find, Negotiate and Close Your Dream Property in',
    'home.country': 'Dominican Republic',
    'home.subtitle': 'Verified catalog with guaranteed transactions, fixed-rate French amortization mortgage simulator, and atomic offer closing.',
    'home.searchAi': 'AI Natural Language Search (NLP)',
    'home.searchQuick': 'Quick Search',
    'home.typeLabel': 'Property Type',
    'home.allTypes': 'All types',
    'home.saleLabel': 'Sale Type',
    'home.allSales': 'All',
    'home.codeLabel': 'Property Code',
    'home.codePlaceholder': 'E.g. 102030',
    'home.exploreBtn': 'Explore Properties',
    'home.statsProps': 'Active Properties',
    'home.statsClients': 'Satisfied Clients',
    'home.statsRate': 'Avg. Fixed Rate',
    'home.statsSecurity': 'Secure Transactions',
    'home.featuredTitle': 'Featured Properties',
    'home.featuredSubtitle': 'Exclusive selection of properties ready for immediate sale and closing in Dominican Pesos.',
    'home.viewAll': 'View Full Catalog',
    'home.whyTitle': 'Why Choose RealEstateApp?',
    'home.whySubtitle': 'An ecosystem engineered to maximize certainty at every stage of real estate transactions.',
    'home.why1Title': 'Banking Mortgage Simulation',
    'home.why1Desc': 'Transparent fixed monthly installments under the French system in Dominican Pesos (RD$) with downloadable amortization schedule.',
    'home.why2Title': 'Atomic Offer Closing',
    'home.why2Desc': 'Guaranteed offer acceptance with automatic cascade cancellation and ACID transactional consistency.',
    'home.why3Title': 'Verified Real Estate Agents',
    'home.why3Desc': 'Certified sales force with KYC verification, personalized support, and live two-way chat.',
    'home.agentsTitle': 'Certified Real Estate Agents',
    'home.agentsSubtitle': 'Meet our team of professional agents dedicated to providing top-tier guidance.',
    'home.viewAgents': 'View All Agents',
    'home.ctaTitle': 'Are You an Owner or Developer?',
    'home.ctaSubtitle': 'List your properties on our platform and connect with thousands of qualified buyers and investors.',
    'home.ctaStart': 'Get Started',
    'home.ctaContact': 'Contact Sales',

    // AI Search
    'ai.searchMode': 'AI Natural Language Search (NLP)',
    'ai.standardMode': 'Standard Search',
    'ai.button': 'Search with AI',
    'ai.buttonShort': 'Search',
    'ai.analyzing': 'Analyzing...',
    'ai.extracting': 'Extracting intent, price ranges, rooms, and locations in real time...',
    'ai.confidence': 'Confidence:',
    'ai.matches': 'matches',
    'ai.match': 'match',
    'ai.placeholder': "Type freely: E.g. '3 bedroom apartment in Bella Vista with balcony under 8M'...",
    'ai.suggestions': 'Suggestions:',
    'ai.understood': 'Interpreted as:',
    'ai.apply': 'Apply Filters',

    // Catalog & Filters
    'catalog.badge': 'Official Properties Catalog',
    'catalog.title': 'Exclusive Properties in DR',
    'catalog.subtitle': 'Filter by type, location, amenities, bedrooms and price ranges with real-time mortgage calculations.',
    'catalog.filters': 'Filters',
    'catalog.activeFilters': 'Active filters:',
    'catalog.clearFilters': 'Clear filters',
    'catalog.clearAll': 'Clear all',
    'catalog.noResults': 'No properties found matching the selected criteria.',
    'catalog.showing': 'Showing',
    'catalog.properties': 'properties',
    'catalog.resultsCount': 'properties found',
    'catalog.sortBy': 'Sort by:',
    'catalog.sortFeatured': 'Featured First',
    'catalog.sortPriceAsc': 'Price: Low to High',
    'catalog.sortPriceDesc': 'Price: High to Low',
    'catalog.sortBedrooms': 'Most Bedrooms',
    'catalog.sortRecent': 'Most Recent',
    'catalog.saveSearch': 'Save Search',
    'catalog.viewGrid': 'Grid',
    'catalog.viewList': 'List',
    'catalog.loading': 'Fetching live catalog...',
    'catalog.emptyTitle': 'No properties found with the selected filters',
    'catalog.emptyDesc': 'Try adjusting your search criteria, widening the price range, or resetting filters.',
    'catalog.modalTitle': 'Save Search',
    'catalog.modalPlaceholder': 'Search name',
    'catalog.modalEmailAlerts': 'Receive email alerts',
    'catalog.cancel': 'Cancel',
    'catalog.save': 'Save',

    // Filter Component
    'filter.title': 'Advanced Filters',
    'filter.reset': 'Reset',
    'filter.code': 'Property Code',
    'filter.codePlaceholder': 'E.g. 102030',
    'filter.type': 'Property Type',
    'filter.allTypes': 'All types',
    'filter.saleType': 'Sale Type',
    'filter.allSales': 'All sale types',
    'filter.priceRange': 'Price Range',
    'filter.minPrice': 'Min Price',
    'filter.maxPrice': 'Max Price',
    'filter.rooms': 'Bedrooms',
    'filter.any': 'Any',
    'filter.orMore': 'or more',
    'filter.bathrooms': 'Bathrooms',
    'filter.location': 'Location',
    'filter.province': 'Province',
    'filter.allProvinces': 'All provinces',
    'filter.municipality': 'Municipality',
    'filter.allMunicipalities': 'All municipalities',
    'filter.sector': 'Sector',
    'filter.sectorPlaceholder': 'E.g. Naco, Piantini, Bella Vista...',
    'filter.nearMe': 'Near me',
    'filter.maxDistance': 'Max distance (km)',
    'filter.amenities': 'Amenities',
    'filter.agent': 'Real Estate Agent',
    'filter.allAgents': 'All agents',
    'filter.onlyFeatured': 'Featured Only',
    'filter.onlyVerified': 'Verified Agents Only',
    'filter.onlyFinanciable': 'Financiable Only',
    'filter.onlyVirtualTour': 'With 360° Tour',

    // Property Card & Details
    'property.featured': 'Featured',
    'property.rooms': 'Beds',
    'property.bathrooms': 'Baths',
    'property.size': 'sqm',
    'property.viewDetails': 'View Details',
    'property.makeOffer': 'Make Offer',
    'property.bookAppointment': 'Schedule Tour',
    'property.virtualTour': '360° Tour',
    'property.estimatedInstallment': 'Est. Installment',
    'property.perMonth': '/mo',
    'property.compare': 'Compare',
    'property.favoritePrompt': 'Sign in as a Client to save favorites.',

    // Mortgage Simulator
    'mortgage.title': 'Mortgage Simulator (RD$)',
    'mortgage.subtitle': 'French Amortization System with fixed monthly installments in Dominican Pesos.',
    'mortgage.propertyPrice': 'Property Price',
    'mortgage.downPayment': 'Down Payment',
    'mortgage.interestRate': 'Annual Interest Rate',
    'mortgage.termYears': 'Term in Years',
    'mortgage.monthlyPayment': 'Estimated Monthly Payment',
    'mortgage.totalLoan': 'Financed Amount',
    'mortgage.totalInterest': 'Total Interest',
    'mortgage.totalPayment': 'Total Payment (Principal + Interest)',
    'mortgage.viewSchedule': 'View Amortization Schedule',
    'mortgage.hideSchedule': 'Hide Schedule',
    'mortgage.disclaimer': 'Indicative calculation excluding bank insurance (life/property insurance not included).',
    'mortgage.scheduleTitle': 'French Amortization Schedule (Fixed Payment)',
    'mortgage.loanTerm': 'Loan Term',
    'mortgage.years': 'Years',
    'mortgage.months': 'months',
    'mortgage.yearsAbbr': 'y',
    'mortgage.fixedInstallment': 'Fixed Monthly Payment',
    'mortgage.forMonths': 'For',
    'mortgage.capitalToFinance': 'Principal to Finance',
    'mortgage.totalCost': 'Total Loan Cost',
    'mortgage.financialCost': 'Accumulated financial cost',
    'mortgage.capitalPlusInterest': 'Principal + Interest',
    'mortgage.fullSchedule': 'View Full Amortization Table',
    'mortgage.hideTable': 'Hide Amortization Table',
    'mortgage.tableTitle': 'Monthly Installment Table — Year',
    'mortgage.tableSubtitle': 'Breakdown of principal amortization and interest distribution.',
    'mortgage.print': 'Print / PDF',
    'mortgage.month': 'Month',
    'mortgage.fixedInstallmentCol': 'Fixed Payment (RD$)',
    'mortgage.interestCol': 'Interest (RD$)',
    'mortgage.principalCol': 'Principal (RD$)',
    'mortgage.balanceCol': 'Remaining Balance (RD$)',
    'mortgage.prevYear': 'Previous Year',
    'mortgage.nextYear': 'Next Year',
    'mortgage.of': 'of',
    'mortgage.year': 'Year',
    'mortgage.annualPayment': 'Annual Payment',
    'mortgage.principal': 'Principal',
    'mortgage.interest': 'Interest',
    'mortgage.balance': 'Remaining Balance',
    'mortgage.downloadPdf': 'Download Schedule',

    // Statuses
    'status.available': 'Available',
    'status.reserved': 'Reserved',
    'status.sold': 'Sold',
    'status.pending': 'Pending',
    'status.accepted': 'Accepted',
    'status.rejected': 'Rejected',
    'status.scheduled': 'Scheduled',
    'status.confirmed': 'Confirmed',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'en' || saved === 'es' ? saved : 'es';
  });

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev) => {
      const next = prev === 'es' ? 'en' : 'es';
      localStorage.setItem(STORAGE_KEY, next);
      return next;
    });
  }, []);

  const t = useCallback(
    (key: string, fallback?: string): string => {
      const dict = TRANSLATIONS[language];
      if (dict && dict[key] !== undefined) {
        return dict[key];
      }
      if (TRANSLATIONS.es[key] !== undefined) {
        return TRANSLATIONS.es[key];
      }
      return fallback || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage debe usarse dentro de un LanguageProvider');
  }
  return ctx;
};
