import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export type Language = 'es' | 'en';

export interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const STORAGE_KEY = 'realestate_language';

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.catalog': 'Catálogo',
    'nav.agents': 'Agentes',
    'nav.mortgage': 'Simulador RD$',
    'nav.map': 'Mapa',
    'nav.compare': 'Comparador',
    'nav.myPanel': 'Mi Panel',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',

    // Sidebar & Portals
    'sidebar.portalClient': 'Portal del Cliente',
    'sidebar.portalOwner': 'Propietario Directo',
    'sidebar.portalAgent': 'Portal del Agente',
    'sidebar.portalAdmin': 'Administración del Sistema',
    'sidebar.coreMaintenance': 'Mantenimientos Núcleo',
    'sidebar.portalDev': 'Portal del Desarrollador',
    'sidebar.panelClient': 'Panel Cliente',
    'sidebar.panelOwner': 'Panel Propietario',
    'sidebar.panelAgent': 'Panel Agente',
    'sidebar.panelAdmin': 'Panel Admin',
    'sidebar.panelDev': 'Panel Dev',
    'sidebar.panelMenu': 'Menú Panel',
    'sidebar.overview': 'Resumen',
    'sidebar.favorites': 'Mis Favoritos',
    'sidebar.offers': 'Mis Ofertas',
    'sidebar.appointments': 'Mis Citas',
    'sidebar.buyAbility': 'Capacidad de Compra',
    'sidebar.savedSearches': 'Búsquedas Guardadas',
    'sidebar.messages': 'Mensajes Directos',
    'sidebar.profile': 'Mi Perfil',
    'sidebar.myProperties': 'Mis Inmuebles',
    'sidebar.publishDirect': 'Publicar Directo',
    'sidebar.receivedOffers': 'Ofertas Recibidas',
    'sidebar.properties': 'Mis Propiedades',
    'sidebar.leadPipeline': 'Pipeline de Prospectos',
    'sidebar.calendar': 'Calendario de Citas',
    'sidebar.commissions': 'Mis Comisiones',
    'sidebar.documents': 'Documentos y KYC',
    'sidebar.subscription': 'Mi Suscripción',
    'sidebar.reviews': 'Mis Reseñas',
    'sidebar.systemKpis': 'KPIs y Métricas',
    'sidebar.allProperties': 'Todas las Propiedades',
    'sidebar.manageAgents': 'Gestionar Agentes',
    'sidebar.reassignPortfolio': 'Reasignar Cartera',
    'sidebar.verifications': 'Verificaciones KYC',
    'sidebar.users': 'Directorio de Usuarios',
    'sidebar.propertyTypes': 'Tipos de Propiedad',
    'sidebar.saleTypes': 'Tipos de Venta',
    'sidebar.improvements': 'Amenidades',
    'sidebar.managePlans': 'Planes de Suscripción',
    'sidebar.manageAdmins': 'Administradores',
    'sidebar.manageDevs': 'Desarrolladores',
    'sidebar.auditActivity': 'Auditoría del Sistema',
    'sidebar.apiPortal': 'Portal de API',
    'sidebar.apiDocs': 'Documentación Swagger',
    'sidebar.rawCatalogs': 'Catálogos RAW',
    'sidebar.roleAdmin': 'Administrador',
    'sidebar.roleAgent': 'Agente',
    'sidebar.roleOwner': 'Propietario',
    'sidebar.roleDeveloper': 'Desarrollador',
    'sidebar.roleClient': 'Cliente',

    // Home Page
    'home.badge': 'Ecosistema Inmobiliario de Alto Rendimiento en RD$',
    'home.title': 'Encuentra, Negocia y Cierra tu Inmueble Soñado en',
    'home.country': 'República Dominicana',
    'home.subtitle': 'Catálogo verificado con transacciones garantizadas, simulación hipotecaria en cuotas fijas bajo el sistema francés y cierre atómico de ofertas.',
    'home.searchAi': 'Búsqueda Inteligente con IA (NLP)',
    'home.searchQuick': 'Búsqueda Rápida',
    'home.typeLabel': 'Tipo de Propiedad',
    'home.allTypes': 'Todos los tipos',
    'home.saleLabel': 'Modalidad',
    'home.allSales': 'Todas',
    'home.codeLabel': 'Código de Propiedad',
    'home.codePlaceholder': 'Ej. 102030',
    'home.exploreBtn': 'Explorar Propiedades',
    'home.statsProps': 'Inmuebles Activos',
    'home.statsClients': 'Clientes Satisfechos',
    'home.statsRate': 'Tasa Promedio Fija',
    'home.statsSecurity': 'Transacciones Seguras',
    'home.featuredTitle': 'Propiedades Destacadas',
    'home.featuredSubtitle': 'Selección exclusiva de inmuebles listos para venta y cierre inmediato en pesos dominicanos.',
    'home.viewAll': 'Ver Catálogo Completo',
    'home.whyTitle': '¿Por Qué Elegir RealEstateApp?',
    'home.whySubtitle': 'Un ecosistema diseñado para maximizar la certidumbre en cada etapa de la compraventa.',
    'home.why1Title': 'Simulación Hipotecaria Bancaria',
    'home.why1Desc': 'Cálculo transparente en cuotas fijas bajo el sistema francés en pesos dominicanos (RD$) con tabla amortizada descargable.',
    'home.why2Title': 'Cierre Atómico de Ofertas',
    'home.why2Desc': 'Aceptación de oferta garantizada con cancelación automática en cascada y consistencia transaccional ACID.',
    'home.why3Title': 'Agentes Inmobiliarios Verificados',
    'home.why3Desc': 'Fuerza de ventas certificada con validación KYC, atención personalizada y chat bidireccional en vivo.',
    'home.agentsTitle': 'Corredores Inmobiliarios Certificados',
    'home.agentsSubtitle': 'Conoce a nuestro equipo de agentes profesionales dedicados a brindarte asesoría de primer nivel.',
    'home.viewAgents': 'Ver Todos los Agentes',
    'home.ctaTitle': '¿Eres Propietario o Desarrollador?',
    'home.ctaSubtitle': 'Publica tus propiedades en nuestra plataforma y conecta con miles de compradores e inversionistas calificados.',
    'home.ctaStart': 'Comenzar Ahora',
    'home.ctaContact': 'Contactar Ventas',

    // AI Search
    'ai.searchMode': 'Búsqueda Inteligente con IA (NLP)',
    'ai.standardMode': 'Búsqueda Estándar',
    'ai.button': 'Buscar con IA',
    'ai.buttonShort': 'Buscar',
    'ai.analyzing': 'Interpretando...',
    'ai.extracting': 'Extrayendo intenciones, rangos de precio, habitaciones y zonas en tiempo real...',
    'ai.confidence': 'Confianza:',
    'ai.matches': 'coincidencias',
    'ai.match': 'coincidencia',
    'ai.placeholder': "Escribe libremente: Ej. 'Apartamento de 3 habitaciones en Bella Vista con balcón por menos de 8M'...",
    'ai.suggestions': 'Sugerencias:',
    'ai.suggestion1': 'Apartamento de 3 habitaciones en Bella Vista por menos de RD$ 8M',
    'ai.suggestion2': 'Villa en Punta Cana con piscina y tour virtual',
    'ai.suggestion3': 'Casa en Santiago de 4 habitaciones con patio',
    'ai.suggestion4': 'Penthouse en Piantini con terraza y ascensor',
    'ai.suggestion5': 'Apartamento en alquiler con 2 baños y gimnasio por menos de 45 mil pesos',
    'ai.understood': 'Interpretado como:',
    'ai.apply': 'Aplicar Filtros',

    'catalog.badge': 'Catálogo Oficial de Inmuebles',
    'catalog.title': 'Propiedades Exclusivas en RD$',
    'catalog.subtitle': 'Filtra por tipo, ubicación, amenidades, habitaciones y rango de precios con cálculo hipotecario en tiempo real.',
    'catalog.filters': 'Filtros',
    'catalog.activeFilters': 'Filtros activos:',
    'catalog.clearFilters': 'Limpiar filtros',
    'catalog.clearAll': 'Limpiar todo',
    'catalog.noResults': 'No se encontraron propiedades con los criterios seleccionados.',
    'catalog.showing': 'Mostrando',
    'catalog.properties': 'inmuebles',
    'catalog.resultsCount': 'propiedades encontradas',
    'catalog.sortBy': 'Ordenar por:',
    'catalog.sortFeatured': 'Destacadas Primero',
    'catalog.sortPriceAsc': 'Precio: Menor a Mayor',
    'catalog.sortPriceDesc': 'Precio: Mayor a Menor',
    'catalog.sortBedrooms': 'Más Habitaciones',
    'catalog.sortRecent': 'Más Recientes',
    'catalog.saveSearch': 'Guardar Búsqueda',
    'catalog.viewGrid': 'Cuadrícula',
    'catalog.viewList': 'Lista',
    'catalog.loading': 'Consultando catálogo en vivo...',
    'catalog.emptyTitle': 'No se encontraron propiedades con los filtros seleccionados',
    'catalog.emptyDesc': 'Intenta ajustar los criterios de búsqueda, ampliar el rango de precios en RD$ o limpiar los filtros.',
    'catalog.modalTitle': 'Guardar Búsqueda',
    'catalog.modalPlaceholder': 'Nombre de la búsqueda',
    'catalog.modalEmailAlerts': 'Recibir alertas por correo',
    'catalog.cancel': 'Cancelar',
    'catalog.save': 'Guardar',

    // Filter Component
    'filter.title': 'Filtros Avanzados',
    'filter.reset': 'Limpiar',
    'filter.code': 'Código de Propiedad',
    'filter.codePlaceholder': 'Ej. 102030',
    'filter.type': 'Tipo de Propiedad',
    'filter.allTypes': 'Todos los tipos',
    'filter.saleType': 'Modalidad de Venta',
    'filter.allSales': 'Todas las modalidades',
    'filter.priceRange': 'Rango de Precios',
    'filter.minPrice': 'Precio Mín',
    'filter.maxPrice': 'Precio Máx',
    'filter.rooms': 'Habitaciones',
    'filter.any': 'Cualquiera',
    'filter.orMore': 'o más',
    'filter.bathrooms': 'Baños',
    'filter.location': 'Ubicación',
    'filter.province': 'Provincia',
    'filter.allProvinces': 'Todas las provincias',
    'filter.municipality': 'Municipio',
    'filter.allMunicipalities': 'Todos los municipios',
    'filter.sector': 'Sector',
    'filter.sectorPlaceholder': 'Ej. Naco, Piantini, Bella Vista...',
    'filter.nearMe': 'Cerca de mí',
    'filter.maxDistance': 'Distancia máxima (km)',
    'filter.amenities': 'Mejoras / Amenidades',
    'filter.agent': 'Agente Inmobiliario',
    'filter.allAgents': 'Todos los agentes',
    'filter.onlyFeatured': 'Solo Destacadas',
    'filter.onlyVerified': 'Solo Agentes Verificados',
    'filter.onlyFinanciable': 'Solo Financiables',
    'filter.onlyVirtualTour': 'Con Tour 360°',

    // Property Card & Details
    'property.featured': 'Destacada',
    'property.rooms': 'Hab.',
    'property.bathrooms': 'Baños',
    'property.size': 'm²',
    'property.viewDetails': 'Ver Detalles',
    'property.makeOffer': 'Hacer Oferta',
    'property.bookAppointment': 'Agendar Cita',
    'property.virtualTour': 'Tour 360°',
    'property.estimatedInstallment': 'Cuota estimada',
    'property.perMonth': '/mes',
    'property.compare': 'Comparar',
    'property.favoritePrompt': 'Inicia sesión como Cliente para guardar favoritos.',

    // Mortgage Simulator
    'mortgage.title': 'Simulador Hipotecario (RD$)',
    'mortgage.subtitle': 'Sistema Francés de Amortización con cuota fija mensual en Pesos Dominicanos.',
    'mortgage.propertyPrice': 'Precio del Inmueble',
    'mortgage.downPayment': 'Inicial',
    'mortgage.interestRate': 'Tasa de Interés Anual',
    'mortgage.termYears': 'Plazo en Años',
    'mortgage.monthlyPayment': 'Cuota Mensual Estimada',
    'mortgage.totalLoan': 'Monto Financiado',
    'mortgage.totalInterest': 'Total Intereses',
    'mortgage.totalPayment': 'Pago Total (Capital + Interés)',
    'mortgage.viewSchedule': 'Ver Tabla de Amortización',
    'mortgage.hideSchedule': 'Ocultar Tabla',
    'mortgage.disclaimer': 'Cálculo orientativo sin seguros bancarios (seguro de vida / propiedad no incluidos).',
    'mortgage.scheduleTitle': 'Tabla de Amortización Francesa (Cuota Fija)',
    'mortgage.loanTerm': 'Plazo del Préstamo',
    'mortgage.years': 'Años',
    'mortgage.months': 'meses',
    'mortgage.yearsAbbr': 'a',
    'mortgage.fixedInstallment': 'Cuota Fija Mensual',
    'mortgage.forMonths': 'Por',
    'mortgage.capitalToFinance': 'Capital a Financiar',
    'mortgage.totalCost': 'Costo Total del Crédito',
    'mortgage.financialCost': 'Costo financiero acumulado',
    'mortgage.capitalPlusInterest': 'Capital + Intereses',
    'mortgage.fullSchedule': 'Ver Tabla de Amortización Completa',
    'mortgage.hideTable': 'Ocultar Tabla de Amortización',
    'mortgage.tableTitle': 'Tabla de Cuotas Mensuales — Año',
    'mortgage.tableSubtitle': 'Desglose de amortización del capital y distribución de intereses.',
    'mortgage.print': 'Imprimir / PDF',
    'mortgage.month': 'Mes',
    'mortgage.fixedInstallmentCol': 'Cuota Fija (RD$)',
    'mortgage.interestCol': 'Interés (RD$)',
    'mortgage.principalCol': 'Capital (RD$)',
    'mortgage.balanceCol': 'Balance Restante (RD$)',
    'mortgage.prevYear': 'Año Anterior',
    'mortgage.nextYear': 'Siguiente Año',
    'mortgage.of': 'de',
    'mortgage.year': 'Año',
    'mortgage.annualPayment': 'Cuota Anual',
    'mortgage.principal': 'Capital',
    'mortgage.interest': 'Interés',
    'mortgage.balance': 'Saldo Restante',
    'mortgage.downloadPdf': 'Descargar Tabla',

    // Statuses
    'status.available': 'Disponible',
    'status.reserved': 'Reservada',
    'status.sold': 'Vendida',
    'status.pending': 'Pendiente',
    'status.accepted': 'Aceptada',
    'status.rejected': 'Rechazada',
    'status.scheduled': 'Programada',
    'status.confirmed': 'Confirmada',
    'status.completed': 'Completada',
    'status.cancelled': 'Cancelada',

    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.close': 'Cerrar',
    'common.actions': 'Acciones',
    'common.details': 'Detalles',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.none': 'Ninguno',
    'common.yes': 'Sí',
    'common.no': 'No',

    // Footer
    'footer.desc': 'Ecosistema transaccional inmobiliario de clase empresarial para República Dominicana. Negociación de ofertas en tiempo real y simulación hipotecaria profesional.',
    'footer.secureTransactions': 'Transacciones Seguras en RD$',
    'footer.navigation': 'Navegación',
    'footer.catalog': 'Catálogo de Inmuebles',
    'footer.simulator': 'Simulador Hipotecario (RD$)',
    'footer.agents': 'Directorio de Corredores',
    'footer.login': 'Acceso al Sistema',
    'footer.platform': 'Plataforma',
    'footer.buyerRegister': 'Registro de Compradores',
    'footer.agentJoin': 'Unirse como Agente Inmobiliario',
    'footer.architecture': 'Arquitectura Onion .NET 10 + React SPA',
    'footer.atomicRule': 'Regla Atómica de Cierre en Cascada',
    'footer.contact': 'Contacto',
    'footer.location': 'Santo Domingo, República Dominicana',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.developedWith': 'Desarrollado con',
    'footer.forMarket': 'para el mercado inmobiliario dominicano',

    // Auth / Login
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Ingresa tus credenciales para acceder a la plataforma inmobiliaria.',
    'login.demoTitle': 'Acceso Rápido para Demostración',
    'login.oneClick': '1 Clic',
    'login.roleAdmin': 'Administrador',
    'login.roleAgent': 'Agente',
    'login.roleClient': 'Cliente Comprador',
    'login.roleDev': 'Desarrollador',
    'login.email': 'Correo Electrónico',
    'login.emailPlaceholder': 'ejemplo@realestate.com',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.submitting': 'Iniciando sesión...',
    'login.submit': 'Entrar a la Plataforma',
    'login.noAccount': '¿No tienes una cuenta aún?',
    'login.registerClient': 'Regístrate como Cliente',
    'login.isAgent': '¿Eres agente inmobiliario?',
    'login.registerAgent': 'Únete como Corredor',
    'login.invalidCredentials': 'Credenciales inválidas.',
    'login.serverError': 'Error al conectar con el servidor.',

    // Admin Dashboard
    'admin.loading': 'Generando cuadro de mando ejecutivo...',
    'admin.badge': 'Dirección Ejecutiva',
    'admin.title': 'Dashboard de KPIs y Control Global',
    'admin.subtitle': 'Métricas de inventario inmobiliario, rendimiento de agentes y usuarios en tiempo real.',
    'admin.manageAgents': 'Gestión de Agentes',
    'admin.coreCatalogs': 'Catálogos Núcleo',
    'admin.availableProperties': 'Inmuebles Disponibles',
    'admin.soldProperties': 'Inmuebles Vendidos',
    'admin.activeAgents': 'Agentes Activos',
    'admin.inactive': 'inactivos',
    'admin.buyerClients': 'Clientes Compradores',
    'admin.statusDistribution': 'Distribución por Estado',
    'admin.statusAvailable': 'Disponibles',
    'admin.statusReserved': 'Reservadas',
    'admin.statusSold': 'Vendidas',
    'admin.total': 'Total',
    'admin.properties': 'Propiedades',
    'admin.noProperties': 'Aún no hay propiedades registradas.',
    'admin.propertiesByType': 'Propiedades por Tipo',
    'admin.units': 'Unidades',
    'admin.noDistributionData': 'No hay datos de distribución disponibles.',
    'admin.governanceTitle': 'Accesos Rápidos de Gobernanza',
    'admin.agentsDesc': 'Activar, inactivar y reasignar cartera',
    'admin.usersTitle': 'Admins & Developers',
    'admin.usersDesc': 'Crear credenciales y accesos REST',
    'admin.propertyTypesTitle': 'Tipos de Inmuebles',
    'admin.propertyTypesDesc': 'Mantenimiento y conteo',
    'admin.improvementsTitle': 'Amenidades y Mejoras',
    'admin.improvementsDesc': 'Catálogo de amenidades',

    // Admin Submenus - Common
    'admin.common.edit': 'Editar',
    'admin.common.delete': 'Eliminar',
    'admin.common.cancel': 'Cancelar',
    'admin.common.actions': 'Acciones',
    'admin.common.save': 'Guardar',
    'admin.common.saving': 'Guardando...',

    // Admin - Manage Agents
    'admin.agents.title': 'Administración de Agentes Inmobiliarios',
    'admin.agents.subtitle': 'Control de cuentas, activación/inactivación, reasignación de cartera y eliminación segura.',
    'admin.agents.searchPlaceholder': 'Buscar agente...',
    'admin.agents.loading': 'Cargando listado de agentes...',
    'admin.agents.colAgent': 'Agente',
    'admin.agents.colContact': 'Contacto',
    'admin.agents.colProperties': 'Propiedades',
    'admin.agents.colStatus': 'Estado',
    'admin.agents.colActions': 'Acciones',
    'admin.agents.noPhone': 'Sin teléfono',
    'admin.agents.activate': 'Activar',
    'admin.agents.deactivate': 'Inactivar',
    'admin.agents.reassign': 'Reasignar',
    'admin.agents.reassignTooltip': 'Reasignar Propiedades a otro Agente',
    'admin.agents.deleteTooltip': 'Eliminar en Cascada',
    'admin.agents.deleteConfirm': '¿Seguro que deseas eliminar a este agente? Esta acción eliminará físicamente en cascada todas sus propiedades e imágenes asociadas.',
    'admin.agents.reassignSuccess': '¡Cartera de propiedades reasignada exitosamente!',
    'admin.agents.reassignError': 'Error al reasignar cartera.',
    'admin.agents.modalTitle': 'Reasignar Cartera de',
    'admin.agents.modalOrigin': 'Agente Origen:',
    'admin.agents.modalTransfer': 'Inmuebles a transferir:',
    'admin.agents.modalProperties': 'propiedades',
    'admin.agents.modalSelectTarget': 'Selecciona el Agente Destino *',
    'admin.agents.modalSelectPlaceholder': 'Selecciona un agente activo...',
    'admin.agents.modalCancel': 'Cancelar',
    'admin.agents.modalTransferring': 'Transfiriendo...',
    'admin.agents.modalConfirm': 'Confirmar Reasignación',

    // Admin - Manage Users
    'admin.users.title': 'Administradores & Desarrolladores API',
    'admin.users.subtitle': 'Gestión de credenciales de gobierno del sistema y accesos técnicos para consumo REST.',
    'admin.users.newAdmin': 'Nuevo Admin',
    'admin.users.newDev': 'Nuevo Developer',
    'admin.users.adminsTab': 'Administradores',
    'admin.users.devsTab': 'Desarrolladores Web API',
    'admin.users.loading': 'Cargando usuarios del sistema...',
    'admin.users.colUser': 'Usuario',
    'admin.users.colEmail': 'Correo',
    'admin.users.colPhone': 'Teléfono',
    'admin.users.colStatus': 'Estado',
    'admin.users.colAction': 'Acción',
    'admin.users.modalCreateTitle': 'Crear Nuevo Usuario',
    'admin.users.firstName': 'Nombre',
    'admin.users.lastName': 'Apellido',
    'admin.users.userName': 'Usuario',
    'admin.users.phone': 'Teléfono',
    'admin.users.email': 'Correo Electrónico',
    'admin.users.password': 'Contraseña',
    'admin.users.confirmPassword': 'Confirmar',
    'admin.users.passwordMismatch': 'Las contraseñas no coinciden.',
    'admin.users.createSuccess': 'creado exitosamente.',
    'admin.users.createError': 'Error al registrar usuario.',
    'admin.users.creating': 'Registrando...',
    'admin.users.createUser': 'Crear Usuario',

    // Admin - Global Properties Catalog
    'admin.allProps.title': 'Catálogo Global de Inmuebles',
    'admin.allProps.subtitle': 'Supervisión integral de todas las propiedades publicadas, reasignación de carteras y destacados.',
    'admin.allProps.searchPlaceholder': 'Buscar por código, tipo, agente...',
    'admin.allProps.loading': 'Cargando catálogo global de inmuebles...',
    'admin.allProps.colCodeType': 'Código / Tipo',
    'admin.allProps.colPrice': 'Precio (RD$)',
    'admin.allProps.colAgent': 'Agente Asignado',
    'admin.allProps.colStatus': 'Estado',
    'admin.allProps.colFeatured': 'Destacado',
    'admin.allProps.colActions': 'Acciones',
    'admin.allProps.noAgent': 'Sin Agente',
    'admin.allProps.featured': 'Destacado',
    'admin.allProps.standard': 'Estándar',
    'admin.allProps.viewPublic': 'Ver Ficha Pública',
    'admin.allProps.reassignAgent': 'Reasignar Agente',
    'admin.allProps.deleteProperty': 'Eliminar Propiedad',
    'admin.allProps.deleteConfirm': '¿Seguro que deseas eliminar esta propiedad del sistema de forma permanente?',
    'admin.allProps.modalTitle': 'Reasignar Propiedad #',
    'admin.allProps.modalDesc': 'Selecciona el agente receptor para transferir la gestión de esta propiedad.',
    'admin.allProps.modalSelectLabel': 'Nuevo Agente *',
    'admin.allProps.modalSelectPlaceholder': 'Selecciona un agente...',
    'admin.allProps.modalConfirm': 'Confirmar Transferencia',
    'admin.allProps.modalTransferring': 'Reasignando...',

    // Admin - Property Types Catalog
    'admin.propType.title': 'Mantenimiento de Tipos de Propiedad',
    'admin.propType.subtitle': 'Gestión del catálogo de categorías de inmuebles (Apartamentos, Casas, Villas, etc.).',
    'admin.propType.new': 'Nuevo Tipo',
    'admin.propType.loading': 'Cargando tipos de propiedad...',
    'admin.propType.colName': 'Nombre',
    'admin.propType.colDesc': 'Descripción',
    'admin.propType.colRegistered': 'Inmuebles Registrados',
    'admin.propType.noDesc': 'Sin descripción',
    'admin.propType.propertiesCount': 'inmuebles',
    'admin.propType.editTitle': 'Editar Tipo de Propiedad',
    'admin.propType.createTitle': 'Crear Nuevo Tipo de Propiedad',
    'admin.propType.nameLabel': 'Nombre *',
    'admin.propType.descLabel': 'Descripción',
    'admin.propType.namePlaceholder': 'Ej: Apartamento, Villa, Penthouse...',
    'admin.propType.descPlaceholder': 'Descripción general de este tipo de inmueble...',
    'admin.propType.save': 'Guardar Tipo',
    'admin.propType.deleteTitle': 'Confirmar Eliminación',
    'admin.propType.deletePrompt': '¿Estás seguro de que deseas eliminar el tipo de propiedad',
    'admin.propType.deleteWarning': 'Esta acción no se puede deshacer.',
    'admin.propType.deleteDefinitely': 'Eliminar Definitivamente',
    'admin.propType.deleteErrorFallback': 'No se puede eliminar este tipo de propiedad porque tiene inmuebles asociados.',

    // Admin - Sale Types Catalog
    'admin.saleType.title': 'Mantenimiento de Tipos de Venta',
    'admin.saleType.subtitle': 'Gestión de modalidades de comercialización (Venta, Alquiler, Alquiler Amueblado, etc.).',
    'admin.saleType.new': 'Nueva Modalidad',
    'admin.saleType.loading': 'Cargando tipos de venta...',
    'admin.saleType.editTitle': 'Editar Tipo de Venta',
    'admin.saleType.createTitle': 'Crear Nuevo Tipo de Venta',
    'admin.saleType.namePlaceholder': 'Ej: Venta, Alquiler, Rent-to-Own...',
    'admin.saleType.descPlaceholder': 'Descripción de la modalidad comercial...',
    'admin.saleType.save': 'Guardar Modalidad',
    'admin.saleType.deleteConfirm': '¿Seguro que deseas eliminar este tipo de venta?',
    'admin.saleType.deleteError': 'No se puede eliminar: tiene propiedades asociadas.',

    // Admin - Improvements Catalog
    'admin.improvement.title': 'Mantenimiento de Amenidades y Mejoras',
    'admin.improvement.subtitle': 'Catálogo de características diferenciales (Piscina, Gimnasio, Planta Eléctrica, Seguridad 24/7, etc.).',
    'admin.improvement.new': 'Nueva Amenidad',
    'admin.improvement.loading': 'Cargando catálogo de amenidades...',
    'admin.improvement.colName': 'Amenidad / Mejora',
    'admin.improvement.editTitle': 'Editar Amenidad',
    'admin.improvement.createTitle': 'Crear Nueva Amenidad',
    'admin.improvement.namePlaceholder': 'Ej: Piscina Infinity, Gimnasio, Ascensor...',
    'admin.improvement.descPlaceholder': 'Descripción de la mejora o amenidad...',
    'admin.improvement.save': 'Guardar Amenidad',
    'admin.improvement.deleteConfirm': '¿Seguro que deseas eliminar esta amenidad?',

    // Admin - Verifications KYC
    'admin.verif.title': 'Validación de Identidad KYC de Agentes',
    'admin.verif.subtitle': 'Revisa las cédulas oficiales y otorga la insignia de Agente Verificado a los corredores aprobados.',
    'admin.verif.all': 'Todos',
    'admin.verif.pending': 'Pendientes',
    'admin.verif.approved': 'Aprobados',
    'admin.verif.empty': 'No hay solicitudes en este estado.',
    'admin.verif.colAgent': 'Agente',
    'admin.verif.colCedula': 'Cédula Oficial',
    'admin.verif.colDocs': 'Documentos',
    'admin.verif.colStatus': 'Estado',
    'admin.verif.colActions': 'Acciones',
    'admin.verif.viewDocs': 'Ver Cédula Front/Back',
    'admin.verif.statusApproved': 'Aprobado',
    'admin.verif.statusPending': 'Pendiente de Revisión',
    'admin.verif.statusRejected': 'Rechazado',
    'admin.verif.approve': 'Aprobar KYC',
    'admin.verif.reject': 'Rechazar',
    'admin.verif.approveConfirm': '¿Aprobar esta verificación KYC y otorgar la insignia de Agente Verificado?',
    'admin.verif.rejectModalTitle': 'Rechazar Solicitud KYC',
    'admin.verif.rejectModalReason': 'Motivo del Rechazo *',
    'admin.verif.rejectModalPlaceholder': 'Indica por qué se rechaza la cédula (borrosa, no legible, vencida)...',
    'admin.verif.confirmReject': 'Confirmar Rechazo',
    'admin.verif.docModalTitle': 'Documento de Identidad Oficial (Cédula)',

    // Admin - Reviews
    'admin.reviews.title': 'Reseñas de Agentes',
    'admin.reviews.subtitle': 'Calificaciones y comentarios de clientes tras completar transacciones.',
    'admin.reviews.loading': 'Cargando reseñas de agentes...',
    'admin.reviews.reviewsCount': 'reseñas',
    'admin.reviews.emptyTitle': 'Aún no hay reseñas registradas',
    'admin.reviews.emptySubtitle': 'Cuando los clientes califiquen a sus agentes tras una compra, aparecerán aquí.',

    // Admin - Commissions
    'admin.commissions.title': 'Comisiones por Venta Inmobiliaria',
    'admin.commissions.subtitle': 'Registro financiero de comisiones generadas por cierres de venta exitosos.',
    'admin.commissions.loading': 'Cargando comisiones...',
    'admin.commissions.totalPaid': 'Comisiones Pagadas',
    'admin.commissions.totalPending': 'Comisiones Pendientes',
    'admin.commissions.markPaid': 'Marcar Pagada',
    'admin.commissions.markPaidConfirm': '¿Marcar esta comisión como PAGADA?',
    'admin.commissions.empty': 'No hay comisiones registradas.',

    // Admin - Documents
    'admin.docs.title': 'Documentos Legales y de Propiedades',
    'admin.docs.subtitle': 'Repositorio centralizado de títulos de propiedad, contratos y planos.',
    'admin.docs.loading': 'Cargando documentos legales...',
    'admin.docs.empty': 'No hay documentos registrados.',
    'admin.docs.deleteConfirm': '¿Eliminar este documento? Esta acción no se puede deshacer.',

    // Admin - Subscriptions
    'admin.subs.title': 'Membresías y Planes de Agentes',
    'admin.subs.subtitle': 'Configuración de tarifas, límites de inmuebles destacados y beneficios para corredores asociados.',
    'admin.subs.newPlan': 'Nuevo Plan',
    'admin.subs.loading': 'Cargando planes de suscripción...',
    'admin.subs.activePlans': 'Planes Activos',
    'admin.subs.revenueModel': 'Modelo de Ingresos',
    'admin.subs.saasRecurring': 'SaaS Recurrente',
    'admin.subs.baseCurrency': 'Moneda Base',
    'admin.subs.rdCurrency': 'Pesos Dominicanos (RD$)',
    'admin.subs.editPlan': 'Editar Plan',
    'admin.subs.newPlanModal': 'Nuevo Plan de Suscripción',
    'admin.subs.planName': 'Nombre del Plan',
    'admin.subs.monthlyPrice': 'Precio Mensual (RD$)',
    'admin.subs.salesCommission': 'Comisión por Venta (%)',
    'admin.subs.maxActiveProps': 'Propiedades Activas Máx.',
    'admin.subs.maxFeaturedProps': 'Destacadas Máx.',
    'admin.subs.description': 'Descripción',
    'admin.subs.tours3D': 'Tours 3D',
    'admin.subs.video': 'Videos',
    'admin.subs.planActive': 'Plan activo (visible para agentes)',
    'admin.subs.cancel': 'Cancelar',
    'admin.subs.saveChanges': 'Guardar Cambios',
    'admin.subs.createPlan': 'Crear Plan',
    'admin.subs.colName': 'Nombre del Plan',
    'admin.subs.colDesc': 'Descripción',
    'admin.subs.colPrice': 'Precio Mensual',
    'admin.subs.colLimits': 'Límites',
    'admin.subs.colCommission': 'Comisión por Venta',
    'admin.subs.colBenefits': 'Beneficios',
    'admin.subs.colStatus': 'Estado',
    'admin.subs.colActions': 'Acciones',
    'admin.subs.free': 'Gratuito',
    'admin.subs.appliesToNew': 'Se aplica a cierres nuevos según el plan del agente.',
    'admin.subs.kycBenefit': 'Verificación KYC',
    'admin.subs.active': 'Activo',
    'admin.subs.inactive': 'Inactivo',
    'admin.subs.empty': 'No hay planes de suscripción registrados. Crea el primero con el botón "Nuevo Plan".',
    'admin.subs.nameRequired': 'El nombre del plan es obligatorio.',
    'admin.subs.negativePrice': 'El precio mensual no puede ser negativo.',
    'admin.subs.errorSaving': 'Error al guardar el plan de suscripción.',
    'admin.subs.deleteConfirm': '¿Eliminar este plan? Esta acción no se puede deshacer.',

    // Admin - Admins
    'admin.admins.title': 'Administración de Administradores',
    'admin.admins.subtitle': 'Gestión de cuentas de administradores del sistema, activación/inactivación y creación.',
    'admin.admins.searchPlaceholder': 'Buscar admin...',
    'admin.admins.newAdmin': 'Nuevo Admin',
    'admin.admins.loading': 'Cargando listado de administradores...',
    'admin.admins.colUser': 'Usuario',
    'admin.admins.colEmail': 'Correo',
    'admin.admins.colPhone': 'Teléfono',
    'admin.admins.colStatus': 'Estado',
    'admin.admins.colActions': 'Acciones',
    'admin.admins.activate': 'Activar',
    'admin.admins.deactivate': 'Inactivar',
    'admin.admins.createTitle': 'Crear Nuevo Administrador',
    'admin.admins.createSubtitle': 'Registra una nueva cuenta de administrador para el panel de control.',
    'admin.admins.createdSuccess': '¡Administrador Creado!',
    'admin.admins.redirecting': 'Redirigiendo al listado de administradores...',
    'admin.admins.firstName': 'Nombre',
    'admin.admins.lastName': 'Apellido',
    'admin.admins.userName': 'Nombre de Usuario',
    'admin.admins.email': 'Correo Electrónico',
    'admin.admins.password': 'Contraseña',
    'admin.admins.confirmPassword': 'Confirmar Contraseña',
    'admin.admins.passwordMismatch': 'Las contraseñas no coinciden.',
    'admin.admins.btnCreate': 'Crear Administrador',
    'admin.admins.creating': 'Creando...',

    // Admin - Developers
    'admin.devs.title': 'Administración de Desarrolladores',
    'admin.devs.subtitle': 'Gestión de cuentas de desarrolladores de la API, activación/inactivación y creación.',
    'admin.devs.searchPlaceholder': 'Buscar desarrollador...',
    'admin.devs.newDev': 'Nuevo Developer',
    'admin.devs.loading': 'Cargando listado de desarrolladores...',
    'admin.devs.loadingData': 'Cargando datos del desarrollador...',
    'admin.devs.colUser': 'Usuario',
    'admin.devs.colEmail': 'Correo',
    'admin.devs.colPhone': 'Teléfono',
    'admin.devs.colStatus': 'Estado',
    'admin.devs.colActions': 'Acciones',
    'admin.devs.activate': 'Activar',
    'admin.devs.deactivate': 'Inactivar',
    'admin.devs.edit': 'Editar',
    'admin.devs.createTitle': 'Crear Nuevo Desarrollador',
    'admin.devs.editTitle': 'Editar Desarrollador',
    'admin.devs.createSubtitle': 'Registra una nueva cuenta de desarrollador para acceso a la API.',
    'admin.devs.editSubtitle': 'Actualiza la información del desarrollador. Deja la contraseña vacía para no cambiarla.',
    'admin.devs.createdSuccess': '¡Desarrollador Creado!',
    'admin.devs.updatedSuccess': '¡Desarrollador Actualizado!',
    'admin.devs.redirecting': 'Redirigiendo al listado de desarrolladores...',
    'admin.devs.btnCreate': 'Crear Desarrollador',
    'admin.devs.btnUpdate': 'Actualizar Desarrollador',
    'admin.devs.saving': 'Guardando...',
  },
  en: {
    // Navigation
    'nav.catalog': 'Catalog',
    'nav.agents': 'Agents',
    'nav.mortgage': 'Mortgage (RD$)',
    'nav.map': 'Map',
    'nav.compare': 'Compare',
    'nav.myPanel': 'Dashboard',
    'nav.login': 'Sign In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',

    // Sidebar & Portals
    'sidebar.portalClient': 'Client Portal',
    'sidebar.portalOwner': 'Direct Owner Portal',
    'sidebar.portalAgent': 'Agent Portal',
    'sidebar.portalAdmin': 'System Administration',
    'sidebar.coreMaintenance': 'Core Maintenance',
    'sidebar.portalDev': 'Developer Portal',
    'sidebar.panelClient': 'Client Panel',
    'sidebar.panelOwner': 'Owner Panel',
    'sidebar.panelAgent': 'Agent Panel',
    'sidebar.panelAdmin': 'Admin Panel',
    'sidebar.panelDev': 'Dev Panel',
    'sidebar.panelMenu': 'Dashboard Menu',
    'sidebar.overview': 'Overview',
    'sidebar.favorites': 'My Favorites',
    'sidebar.offers': 'My Offers',
    'sidebar.appointments': 'My Appointments',
    'sidebar.buyAbility': 'Buying Ability',
    'sidebar.savedSearches': 'Saved Searches',
    'sidebar.messages': 'Direct Messages',
    'sidebar.profile': 'My Profile',
    'sidebar.myProperties': 'My Properties',
    'sidebar.publishDirect': 'Publish Listing',
    'sidebar.receivedOffers': 'Received Offers',
    'sidebar.properties': 'My Properties',
    'sidebar.leadPipeline': 'Lead Pipeline',
    'sidebar.calendar': 'Appointments Calendar',
    'sidebar.commissions': 'My Commissions',
    'sidebar.documents': 'Documents & KYC',
    'sidebar.subscription': 'My Subscription',
    'sidebar.reviews': 'My Reviews',
    'sidebar.systemKpis': 'KPIs & Metrics',
    'sidebar.allProperties': 'All Properties',
    'sidebar.manageAgents': 'Manage Agents',
    'sidebar.reassignPortfolio': 'Reassign Portfolio',
    'sidebar.verifications': 'KYC Verifications',
    'sidebar.users': 'User Directory',
    'sidebar.propertyTypes': 'Property Types',
    'sidebar.saleTypes': 'Sale Types',
    'sidebar.improvements': 'Amenities',
    'sidebar.managePlans': 'Subscription Plans',
    'sidebar.manageAdmins': 'Administrators',
    'sidebar.manageDevs': 'Developers',
    'sidebar.auditActivity': 'System Audit',
    'sidebar.apiPortal': 'API Portal',
    'sidebar.apiDocs': 'Swagger Docs',
    'sidebar.rawCatalogs': 'RAW Catalogs',
    'sidebar.roleAdmin': 'Administrator',
    'sidebar.roleAgent': 'Agent',
    'sidebar.roleOwner': 'Owner',
    'sidebar.roleDeveloper': 'Developer',
    'sidebar.roleClient': 'Client',

    // Home Page
    'home.badge': 'High-Performance Real Estate Ecosystem in DR',
    'home.title': 'Find, Negotiate and Close Your Dream Property in',
    'home.country': 'Dominican Republic',
    'home.subtitle': 'Verified catalog with guaranteed transactions, fixed-rate French amortization mortgage simulator, and atomic offer closing.',
    'home.searchAi': 'AI Natural Language Search (NLP)',
    'home.searchQuick': 'Quick Search',
    'home.typeLabel': 'Property Type',
    'home.allTypes': 'All types',
    'home.saleLabel': 'Sale Type',
    'home.allSales': 'All',
    'home.codeLabel': 'Property Code',
    'home.codePlaceholder': 'E.g. 102030',
    'home.exploreBtn': 'Explore Properties',
    'home.statsProps': 'Active Properties',
    'home.statsClients': 'Satisfied Clients',
    'home.statsRate': 'Avg. Fixed Rate',
    'home.statsSecurity': 'Secure Transactions',
    'home.featuredTitle': 'Featured Properties',
    'home.featuredSubtitle': 'Exclusive selection of properties ready for immediate sale and closing in Dominican Pesos.',
    'home.viewAll': 'View Full Catalog',
    'home.whyTitle': 'Why Choose RealEstateApp?',
    'home.whySubtitle': 'An ecosystem engineered to maximize certainty at every stage of real estate transactions.',
    'home.why1Title': 'Banking Mortgage Simulation',
    'home.why1Desc': 'Transparent fixed monthly installments under the French system in Dominican Pesos (RD$) with downloadable amortization schedule.',
    'home.why2Title': 'Atomic Offer Closing',
    'home.why2Desc': 'Guaranteed offer acceptance with automatic cascade cancellation and ACID transactional consistency.',
    'home.why3Title': 'Verified Real Estate Agents',
    'home.why3Desc': 'Certified sales force with KYC verification, personalized support, and live two-way chat.',
    'home.agentsTitle': 'Certified Real Estate Agents',
    'home.agentsSubtitle': 'Meet our team of professional agents dedicated to providing top-tier guidance.',
    'home.viewAgents': 'View All Agents',
    'home.ctaTitle': 'Are You an Owner or Developer?',
    'home.ctaSubtitle': 'List your properties on our platform and connect with thousands of qualified buyers and investors.',
    'home.ctaStart': 'Get Started',
    'home.ctaContact': 'Contact Sales',

    // AI Search
    'ai.searchMode': 'AI Natural Language Search (NLP)',
    'ai.standardMode': 'Standard Search',
    'ai.button': 'Search with AI',
    'ai.buttonShort': 'Search',
    'ai.analyzing': 'Analyzing...',
    'ai.extracting': 'Extracting intent, price ranges, rooms, and locations in real time...',
    'ai.confidence': 'Confidence:',
    'ai.matches': 'matches',
    'ai.match': 'match',
    'ai.placeholder': "Type freely: E.g. '3 bedroom apartment in Bella Vista with balcony under 8M'...",
    'ai.suggestions': 'Suggestions:',
    'ai.suggestion1': '3 bedroom apartment in Bella Vista under RD$ 8M',
    'ai.suggestion2': 'Villa in Punta Cana with pool and virtual tour',
    'ai.suggestion3': '4 bedroom house in Santiago with yard',
    'ai.suggestion4': 'Penthouse in Piantini with terrace and elevator',
    'ai.suggestion5': 'Apartment for rent with 2 bathrooms and gym under 45k',
    'ai.understood': 'Interpreted as:',
    'ai.apply': 'Apply Filters',

    // Catalog & Filters
    'catalog.badge': 'Official Properties Catalog',
    'catalog.title': 'Exclusive Properties in DR',
    'catalog.subtitle': 'Filter by type, location, amenities, bedrooms and price ranges with real-time mortgage calculations.',
    'catalog.filters': 'Filters',
    'catalog.activeFilters': 'Active filters:',
    'catalog.clearFilters': 'Clear filters',
    'catalog.clearAll': 'Clear all',
    'catalog.noResults': 'No properties found matching the selected criteria.',
    'catalog.showing': 'Showing',
    'catalog.properties': 'properties',
    'catalog.resultsCount': 'properties found',
    'catalog.sortBy': 'Sort by:',
    'catalog.sortFeatured': 'Featured First',
    'catalog.sortPriceAsc': 'Price: Low to High',
    'catalog.sortPriceDesc': 'Price: High to Low',
    'catalog.sortBedrooms': 'Most Bedrooms',
    'catalog.sortRecent': 'Most Recent',
    'catalog.saveSearch': 'Save Search',
    'catalog.viewGrid': 'Grid',
    'catalog.viewList': 'List',
    'catalog.loading': 'Fetching live catalog...',
    'catalog.emptyTitle': 'No properties found with the selected filters',
    'catalog.emptyDesc': 'Try adjusting your search criteria, widening the price range, or resetting filters.',
    'catalog.modalTitle': 'Save Search',
    'catalog.modalPlaceholder': 'Search name',
    'catalog.modalEmailAlerts': 'Receive email alerts',
    'catalog.cancel': 'Cancel',
    'catalog.save': 'Save',

    // Filter Component
    'filter.title': 'Advanced Filters',
    'filter.reset': 'Reset',
    'filter.code': 'Property Code',
    'filter.codePlaceholder': 'E.g. 102030',
    'filter.type': 'Property Type',
    'filter.allTypes': 'All types',
    'filter.saleType': 'Sale Type',
    'filter.allSales': 'All sale types',
    'filter.priceRange': 'Price Range',
    'filter.minPrice': 'Min Price',
    'filter.maxPrice': 'Max Price',
    'filter.rooms': 'Bedrooms',
    'filter.any': 'Any',
    'filter.orMore': 'or more',
    'filter.bathrooms': 'Bathrooms',
    'filter.location': 'Location',
    'filter.province': 'Province',
    'filter.allProvinces': 'All provinces',
    'filter.municipality': 'Municipality',
    'filter.allMunicipalities': 'All municipalities',
    'filter.sector': 'Sector',
    'filter.sectorPlaceholder': 'E.g. Naco, Piantini, Bella Vista...',
    'filter.nearMe': 'Near me',
    'filter.maxDistance': 'Max distance (km)',
    'filter.amenities': 'Amenities',
    'filter.agent': 'Real Estate Agent',
    'filter.allAgents': 'All agents',
    'filter.onlyFeatured': 'Featured Only',
    'filter.onlyVerified': 'Verified Agents Only',
    'filter.onlyFinanciable': 'Financiable Only',
    'filter.onlyVirtualTour': 'With 360° Tour',

    // Property Card & Details
    'property.featured': 'Featured',
    'property.rooms': 'Beds',
    'property.bathrooms': 'Baths',
    'property.size': 'sqm',
    'property.viewDetails': 'View Details',
    'property.makeOffer': 'Make Offer',
    'property.bookAppointment': 'Schedule Tour',
    'property.virtualTour': '360° Tour',
    'property.estimatedInstallment': 'Est. Installment',
    'property.perMonth': '/mo',
    'property.compare': 'Compare',
    'property.favoritePrompt': 'Sign in as a Client to save favorites.',

    // Mortgage Simulator
    'mortgage.title': 'Mortgage Simulator (RD$)',
    'mortgage.subtitle': 'French Amortization System with fixed monthly installments in Dominican Pesos.',
    'mortgage.propertyPrice': 'Property Price',
    'mortgage.downPayment': 'Down Payment',
    'mortgage.interestRate': 'Annual Interest Rate',
    'mortgage.termYears': 'Term in Years',
    'mortgage.monthlyPayment': 'Estimated Monthly Payment',
    'mortgage.totalLoan': 'Financed Amount',
    'mortgage.totalInterest': 'Total Interest',
    'mortgage.totalPayment': 'Total Payment (Principal + Interest)',
    'mortgage.viewSchedule': 'View Amortization Schedule',
    'mortgage.hideSchedule': 'Hide Schedule',
    'mortgage.disclaimer': 'Indicative calculation excluding bank insurance (life/property insurance not included).',
    'mortgage.scheduleTitle': 'French Amortization Schedule (Fixed Payment)',
    'mortgage.loanTerm': 'Loan Term',
    'mortgage.years': 'Years',
    'mortgage.months': 'months',
    'mortgage.yearsAbbr': 'y',
    'mortgage.fixedInstallment': 'Fixed Monthly Payment',
    'mortgage.forMonths': 'For',
    'mortgage.capitalToFinance': 'Principal to Finance',
    'mortgage.totalCost': 'Total Loan Cost',
    'mortgage.financialCost': 'Accumulated financial cost',
    'mortgage.capitalPlusInterest': 'Principal + Interest',
    'mortgage.fullSchedule': 'View Full Amortization Table',
    'mortgage.hideTable': 'Hide Amortization Table',
    'mortgage.tableTitle': 'Monthly Installment Table — Year',
    'mortgage.tableSubtitle': 'Breakdown of principal amortization and interest distribution.',
    'mortgage.print': 'Print / PDF',
    'mortgage.month': 'Month',
    'mortgage.fixedInstallmentCol': 'Fixed Payment (RD$)',
    'mortgage.interestCol': 'Interest (RD$)',
    'mortgage.principalCol': 'Principal (RD$)',
    'mortgage.balanceCol': 'Remaining Balance (RD$)',
    'mortgage.prevYear': 'Previous Year',
    'mortgage.nextYear': 'Next Year',
    'mortgage.of': 'of',
    'mortgage.year': 'Year',
    'mortgage.annualPayment': 'Annual Payment',
    'mortgage.principal': 'Principal',
    'mortgage.interest': 'Interest',
    'mortgage.balance': 'Remaining Balance',
    'mortgage.downloadPdf': 'Download Schedule',

    // Statuses
    'status.available': 'Available',
    'status.reserved': 'Reserved',
    'status.sold': 'Sold',
    'status.pending': 'Pending',
    'status.accepted': 'Accepted',
    'status.rejected': 'Rejected',
    'status.scheduled': 'Scheduled',
    'status.confirmed': 'Confirmed',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',

    // Footer
    'footer.desc': 'Enterprise-grade transactional real estate ecosystem for the Dominican Republic. Real-time offer negotiation and professional mortgage simulation.',
    'footer.secureTransactions': 'Secure Transactions in RD$',
    'footer.navigation': 'Navigation',
    'footer.catalog': 'Property Catalog',
    'footer.simulator': 'Mortgage Simulator (RD$)',
    'footer.agents': 'Brokers Directory',
    'footer.login': 'System Login',
    'footer.platform': 'Platform',
    'footer.buyerRegister': 'Buyer Registration',
    'footer.agentJoin': 'Join as Real Estate Agent',
    'footer.architecture': 'Onion Architecture .NET 10 + React SPA',
    'footer.atomicRule': 'Atomic Cascade Closing Rule',
    'footer.contact': 'Contact',
    'footer.location': 'Santo Domingo, Dominican Republic',
    'footer.rights': 'All rights reserved.',
    'footer.developedWith': 'Developed with',
    'footer.forMarket': 'for the Dominican real estate market',

    // Auth / Login
    'login.title': 'Sign In',
    'login.subtitle': 'Enter your credentials to access the real estate platform.',
    'login.demoTitle': 'Quick Demo Access',
    'login.oneClick': '1-Click',
    'login.roleAdmin': 'Administrator',
    'login.roleAgent': 'Agent',
    'login.roleClient': 'Buyer Client',
    'login.roleDev': 'Developer',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'example@realestate.com',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.submitting': 'Signing in...',
    'login.submit': 'Enter Platform',
    'login.noAccount': "Don't have an account yet?",
    'login.registerClient': 'Register as Client',
    'login.isAgent': 'Are you a real estate agent?',
    'login.registerAgent': 'Join as Broker',
    'login.invalidCredentials': 'Invalid credentials.',
    'login.serverError': 'Error connecting to the server.',

    // Admin Dashboard
    'admin.loading': 'Generating executive dashboard...',
    'admin.badge': 'Executive Management',
    'admin.title': 'KPI Dashboard & Global Control',
    'admin.subtitle': 'Real estate inventory metrics, agent performance, and users in real time.',
    'admin.manageAgents': 'Manage Agents',
    'admin.coreCatalogs': 'Core Catalogs',
    'admin.availableProperties': 'Available Properties',
    'admin.soldProperties': 'Sold Properties',
    'admin.activeAgents': 'Active Agents',
    'admin.inactive': 'inactive',
    'admin.buyerClients': 'Buyer Clients',
    'admin.statusDistribution': 'Distribution by Status',
    'admin.statusAvailable': 'Available',
    'admin.statusReserved': 'Reserved',
    'admin.statusSold': 'Sold',
    'admin.total': 'Total',
    'admin.properties': 'Properties',
    'admin.noProperties': 'No properties registered yet.',
    'admin.propertiesByType': 'Properties by Type',
    'admin.units': 'Units',
    'admin.noDistributionData': 'No distribution data available.',
    'admin.governanceTitle': 'Governance Quick Shortcuts',
    'admin.agentsDesc': 'Activate, deactivate, and reassign portfolio',
    'admin.usersTitle': 'Admins & Developers',
    'admin.usersDesc': 'Create credentials and REST access',
    'admin.propertyTypesTitle': 'Property Types',
    'admin.propertyTypesDesc': 'Maintenance and counts',
    'admin.improvementsTitle': 'Amenities & Improvements',
    'admin.improvementsDesc': 'Amenities catalog',

    // Admin Submenus - Common
    'admin.common.edit': 'Edit',
    'admin.common.delete': 'Delete',
    'admin.common.cancel': 'Cancel',
    'admin.common.actions': 'Actions',
    'admin.common.save': 'Save',
    'admin.common.saving': 'Saving...',

    // Admin - Manage Agents
    'admin.agents.title': 'Real Estate Agents Administration',
    'admin.agents.subtitle': 'Account control, activation/deactivation, portfolio reassignment, and safe deletion.',
    'admin.agents.searchPlaceholder': 'Search agent...',
    'admin.agents.loading': 'Loading agents list...',
    'admin.agents.colAgent': 'Agent',
    'admin.agents.colContact': 'Contact',
    'admin.agents.colProperties': 'Properties',
    'admin.agents.colStatus': 'Status',
    'admin.agents.colActions': 'Actions',
    'admin.agents.noPhone': 'No phone',
    'admin.agents.activate': 'Activate',
    'admin.agents.deactivate': 'Deactivate',
    'admin.agents.reassign': 'Reassign',
    'admin.agents.reassignTooltip': 'Reassign Properties to another Agent',
    'admin.agents.deleteTooltip': 'Cascade Delete',
    'admin.agents.deleteConfirm': 'Are you sure you want to delete this agent? This action will cascade delete all associated properties and images.',
    'admin.agents.reassignSuccess': 'Property portfolio reassigned successfully!',
    'admin.agents.reassignError': 'Error reassigning portfolio.',
    'admin.agents.modalTitle': 'Reassign Portfolio of',
    'admin.agents.modalOrigin': 'Origin Agent:',
    'admin.agents.modalTransfer': 'Properties to transfer:',
    'admin.agents.modalProperties': 'properties',
    'admin.agents.modalSelectTarget': 'Select Target Agent *',
    'admin.agents.modalSelectPlaceholder': 'Select an active agent...',
    'admin.agents.modalCancel': 'Cancel',
    'admin.agents.modalTransferring': 'Transferring...',
    'admin.agents.modalConfirm': 'Confirm Reassignment',

    // Admin - Manage Users
    'admin.users.title': 'Administrators & API Developers',
    'admin.users.subtitle': 'System governance credentials and technical REST access management.',
    'admin.users.newAdmin': 'New Admin',
    'admin.users.newDev': 'New Developer',
    'admin.users.adminsTab': 'Administrators',
    'admin.users.devsTab': 'Web API Developers',
    'admin.users.loading': 'Loading system users...',
    'admin.users.colUser': 'User',
    'admin.users.colEmail': 'Email',
    'admin.users.colPhone': 'Phone',
    'admin.users.colStatus': 'Status',
    'admin.users.colAction': 'Action',
    'admin.users.modalCreateTitle': 'Create New User',
    'admin.users.firstName': 'First Name',
    'admin.users.lastName': 'Last Name',
    'admin.users.userName': 'Username',
    'admin.users.phone': 'Phone',
    'admin.users.email': 'Email Address',
    'admin.users.password': 'Password',
    'admin.users.confirmPassword': 'Confirm Password',
    'admin.users.passwordMismatch': 'Passwords do not match.',
    'admin.users.createSuccess': 'created successfully.',
    'admin.users.createError': 'Error registering user.',
    'admin.users.creating': 'Registering...',
    'admin.users.createUser': 'Create User',

    // Admin - Global Properties Catalog
    'admin.allProps.title': 'Global Property Catalog',
    'admin.allProps.subtitle': 'Comprehensive supervision of all published properties, portfolio reassignment, and featured listings.',
    'admin.allProps.searchPlaceholder': 'Search by code, type, agent...',
    'admin.allProps.loading': 'Loading global property catalog...',
    'admin.allProps.colCodeType': 'Code / Type',
    'admin.allProps.colPrice': 'Price (RD$)',
    'admin.allProps.colAgent': 'Assigned Agent',
    'admin.allProps.colStatus': 'Status',
    'admin.allProps.colFeatured': 'Featured',
    'admin.allProps.colActions': 'Actions',
    'admin.allProps.noAgent': 'No Agent',
    'admin.allProps.featured': 'Featured',
    'admin.allProps.standard': 'Standard',
    'admin.allProps.viewPublic': 'View Public Listing',
    'admin.allProps.reassignAgent': 'Reassign Agent',
    'admin.allProps.deleteProperty': 'Delete Property',
    'admin.allProps.deleteConfirm': 'Are you sure you want to permanently delete this property from the system?',
    'admin.allProps.modalTitle': 'Reassign Property #',
    'admin.allProps.modalDesc': 'Select the receiving agent to transfer management of this property.',
    'admin.allProps.modalSelectLabel': 'New Agent *',
    'admin.allProps.modalSelectPlaceholder': 'Select an agent...',
    'admin.allProps.modalConfirm': 'Confirm Transfer',
    'admin.allProps.modalTransferring': 'Reassigning...',

    // Admin - Property Types Catalog
    'admin.propType.title': 'Property Types Maintenance',
    'admin.propType.subtitle': 'Management of property category catalog (Apartments, Houses, Villas, etc.).',
    'admin.propType.new': 'New Type',
    'admin.propType.loading': 'Loading property types...',
    'admin.propType.colName': 'Name',
    'admin.propType.colDesc': 'Description',
    'admin.propType.colRegistered': 'Registered Properties',
    'admin.propType.noDesc': 'No description',
    'admin.propType.propertiesCount': 'properties',
    'admin.propType.editTitle': 'Edit Property Type',
    'admin.propType.createTitle': 'Create New Property Type',
    'admin.propType.nameLabel': 'Name *',
    'admin.propType.descLabel': 'Description',
    'admin.propType.namePlaceholder': 'E.g.: Apartment, Villa, Penthouse...',
    'admin.propType.descPlaceholder': 'General description of this property type...',
    'admin.propType.save': 'Save Type',
    'admin.propType.deleteTitle': 'Confirm Deletion',
    'admin.propType.deletePrompt': 'Are you sure you want to delete the property type',
    'admin.propType.deleteWarning': 'This action cannot be undone.',
    'admin.propType.deleteDefinitely': 'Delete Permanently',
    'admin.propType.deleteErrorFallback': 'Cannot delete this property type because it has associated properties.',

    // Admin - Sale Types Catalog
    'admin.saleType.title': 'Sale Types Maintenance',
    'admin.saleType.subtitle': 'Management of marketing modalities (Sale, Rent, Furnished Rent, etc.).',
    'admin.saleType.new': 'New Modality',
    'admin.saleType.loading': 'Loading sale types...',
    'admin.saleType.editTitle': 'Edit Sale Type',
    'admin.saleType.createTitle': 'Create New Sale Type',
    'admin.saleType.namePlaceholder': 'E.g.: Sale, Rent, Rent-to-Own...',
    'admin.saleType.descPlaceholder': 'Description of the commercial modality...',
    'admin.saleType.save': 'Save Modality',
    'admin.saleType.deleteConfirm': 'Are you sure you want to delete this sale type?',
    'admin.saleType.deleteError': 'Cannot delete: has associated properties.',

    // Admin - Improvements Catalog
    'admin.improvement.title': 'Amenities & Improvements Maintenance',
    'admin.improvement.subtitle': 'Catalog of distinctive features (Pool, Gym, Power Generator, 24/7 Security, etc.).',
    'admin.improvement.new': 'New Amenity',
    'admin.improvement.loading': 'Loading amenities catalog...',
    'admin.improvement.colName': 'Amenity / Improvement',
    'admin.improvement.editTitle': 'Edit Amenity',
    'admin.improvement.createTitle': 'Create New Amenity',
    'admin.improvement.namePlaceholder': 'E.g.: Infinity Pool, Gym, Elevator...',
    'admin.improvement.descPlaceholder': 'Description of the improvement or amenity...',
    'admin.improvement.save': 'Save Amenity',
    'admin.improvement.deleteConfirm': 'Are you sure you want to delete this amenity?',

    // Admin - Verifications KYC
    'admin.verif.title': 'Agent KYC Identity Verification',
    'admin.verif.subtitle': 'Review official IDs and grant Verified Agent badge to approved brokers.',
    'admin.verif.all': 'All',
    'admin.verif.pending': 'Pending',
    'admin.verif.approved': 'Approved',
    'admin.verif.empty': 'No requests in this status.',
    'admin.verif.colAgent': 'Agent',
    'admin.verif.colCedula': 'Official ID',
    'admin.verif.colDocs': 'Documents',
    'admin.verif.colStatus': 'Status',
    'admin.verif.colActions': 'Actions',
    'admin.verif.viewDocs': 'View ID Front/Back',
    'admin.verif.statusApproved': 'Approved',
    'admin.verif.statusPending': 'Pending Review',
    'admin.verif.statusRejected': 'Rejected',
    'admin.verif.approve': 'Approve KYC',
    'admin.verif.reject': 'Reject',
    'admin.verif.approveConfirm': 'Approve this KYC verification and grant Verified Agent badge?',
    'admin.verif.rejectModalTitle': 'Reject KYC Request',
    'admin.verif.rejectModalReason': 'Rejection Reason *',
    'admin.verif.rejectModalPlaceholder': 'Indicate why ID is rejected (blurry, unreadable, expired)...',
    'admin.verif.confirmReject': 'Confirm Rejection',
    'admin.verif.docModalTitle': 'Official Identity Document (ID)',

    // Admin - Reviews
    'admin.reviews.title': 'Agent Reviews',
    'admin.reviews.subtitle': 'Client ratings and comments after completing transactions.',
    'admin.reviews.loading': 'Loading agent reviews...',
    'admin.reviews.reviewsCount': 'reviews',
    'admin.reviews.emptyTitle': 'No reviews registered yet',
    'admin.reviews.emptySubtitle': 'When clients rate their agents after a purchase, they will appear here.',

    // Admin - Commissions
    'admin.commissions.title': 'Real Estate Sales Commissions',
    'admin.commissions.subtitle': 'Financial record of commissions generated from successful sales closings.',
    'admin.commissions.loading': 'Loading commissions...',
    'admin.commissions.totalPaid': 'Paid Commissions',
    'admin.commissions.totalPending': 'Pending Commissions',
    'admin.commissions.markPaid': 'Mark as Paid',
    'admin.commissions.markPaidConfirm': 'Mark this commission as PAID?',
    'admin.commissions.empty': 'No commissions registered.',

    // Admin - Documents
    'admin.docs.title': 'Legal and Property Documents',
    'admin.docs.subtitle': 'Centralized repository of property titles, contracts, and floor plans.',
    'admin.docs.loading': 'Loading legal documents...',
    'admin.docs.empty': 'No documents registered.',
    'admin.docs.deleteConfirm': 'Delete this document? This action cannot be undone.',

    // Admin - Subscriptions
    'admin.subs.title': 'Agent Memberships & Plans',
    'admin.subs.subtitle': 'Fee settings, featured property limits, and benefits for associated brokers.',
    'admin.subs.newPlan': 'New Plan',
    'admin.subs.loading': 'Loading subscription plans...',
    'admin.subs.activePlans': 'Active Plans',
    'admin.subs.revenueModel': 'Revenue Model',
    'admin.subs.saasRecurring': 'Recurring SaaS',
    'admin.subs.baseCurrency': 'Base Currency',
    'admin.subs.rdCurrency': 'Dominican Pesos (RD$)',
    'admin.subs.editPlan': 'Edit Plan',
    'admin.subs.newPlanModal': 'New Subscription Plan',
    'admin.subs.planName': 'Plan Name',
    'admin.subs.monthlyPrice': 'Monthly Price (RD$)',
    'admin.subs.salesCommission': 'Sales Commission (%)',
    'admin.subs.maxActiveProps': 'Max Active Properties',
    'admin.subs.maxFeaturedProps': 'Max Featured Properties',
    'admin.subs.description': 'Description',
    'admin.subs.tours3D': '3D Tours',
    'admin.subs.video': 'Videos',
    'admin.subs.planActive': 'Active plan (visible to agents)',
    'admin.subs.cancel': 'Cancel',
    'admin.subs.saveChanges': 'Save Changes',
    'admin.subs.createPlan': 'Create Plan',
    'admin.subs.colName': 'Plan Name',
    'admin.subs.colDesc': 'Description',
    'admin.subs.colPrice': 'Monthly Price',
    'admin.subs.colLimits': 'Limits',
    'admin.subs.colCommission': 'Sales Commission',
    'admin.subs.colBenefits': 'Benefits',
    'admin.subs.colStatus': 'Status',
    'admin.subs.colActions': 'Actions',
    'admin.subs.free': 'Free',
    'admin.subs.appliesToNew': 'Applies to new closings according to agent plan.',
    'admin.subs.kycBenefit': 'KYC Verification',
    'admin.subs.active': 'Active',
    'admin.subs.inactive': 'Inactive',
    'admin.subs.empty': 'No subscription plans registered. Create the first one with "New Plan" button.',
    'admin.subs.nameRequired': 'Plan name is required.',
    'admin.subs.negativePrice': 'Monthly price cannot be negative.',
    'admin.subs.errorSaving': 'Error saving subscription plan.',
    'admin.subs.deleteConfirm': 'Delete this plan? This action cannot be undone.',

    // Admin - Admins
    'admin.admins.title': 'Administrators Management',
    'admin.admins.subtitle': 'Management of system administrator accounts, activation/inactivation, and creation.',
    'admin.admins.searchPlaceholder': 'Search admin...',
    'admin.admins.newAdmin': 'New Admin',
    'admin.admins.loading': 'Loading administrators list...',
    'admin.admins.colUser': 'User',
    'admin.admins.colEmail': 'Email',
    'admin.admins.colPhone': 'Phone',
    'admin.admins.colStatus': 'Status',
    'admin.admins.colActions': 'Actions',
    'admin.admins.activate': 'Activate',
    'admin.admins.deactivate': 'Deactivate',
    'admin.admins.createTitle': 'Create New Administrator',
    'admin.admins.createSubtitle': 'Register a new administrator account for the control panel.',
    'admin.admins.createdSuccess': 'Administrator Created!',
    'admin.admins.redirecting': 'Redirecting to administrators list...',
    'admin.admins.firstName': 'First Name',
    'admin.admins.lastName': 'Last Name',
    'admin.admins.userName': 'Username',
    'admin.admins.email': 'Email',
    'admin.admins.password': 'Password',
    'admin.admins.confirmPassword': 'Confirm Password',
    'admin.admins.passwordMismatch': 'Passwords do not match.',
    'admin.admins.btnCreate': 'Create Administrator',
    'admin.admins.creating': 'Creating...',

    // Admin - Developers
    'admin.devs.title': 'Developers Management',
    'admin.devs.subtitle': 'Management of API developer accounts, activation/inactivation, and creation.',
    'admin.devs.searchPlaceholder': 'Search developer...',
    'admin.devs.newDev': 'New Developer',
    'admin.devs.loading': 'Loading developers list...',
    'admin.devs.loadingData': 'Loading developer data...',
    'admin.devs.colUser': 'User',
    'admin.devs.colEmail': 'Email',
    'admin.devs.colPhone': 'Phone',
    'admin.devs.colStatus': 'Status',
    'admin.devs.colActions': 'Actions',
    'admin.devs.activate': 'Activate',
    'admin.devs.deactivate': 'Deactivate',
    'admin.devs.edit': 'Edit',
    'admin.devs.createTitle': 'Create New Developer',
    'admin.devs.editTitle': 'Edit Developer',
    'admin.devs.createSubtitle': 'Register a new developer account for API access.',
    'admin.devs.editSubtitle': 'Update developer information. Leave password empty to keep it.',
    'admin.devs.createdSuccess': 'Developer Created!',
    'admin.devs.updatedSuccess': 'Developer Updated!',
    'admin.devs.redirecting': 'Redirecting to developers list...',
    'admin.devs.btnCreate': 'Create Developer',
    'admin.devs.btnUpdate': 'Update Developer',
    'admin.devs.saving': 'Saving...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'en' || saved === 'es' ? saved : 'es';
  });

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev) => {
      const next = prev === 'es' ? 'en' : 'es';
      localStorage.setItem(STORAGE_KEY, next);
      return next;
    });
  }, []);

  const t = useCallback(
    (key: string, fallback?: string): string => {
      const dict = TRANSLATIONS[language];
      if (dict && dict[key] !== undefined) {
        return dict[key];
      }
      if (TRANSLATIONS.es[key] !== undefined) {
        return TRANSLATIONS.es[key];
      }
      return fallback || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage debe usarse dentro de un LanguageProvider');
  }
  return ctx;
};
